/**
 * The language list is generated by language_list.py
 * and filtered manually.
 */
var langs = [["ada", "Ada"], ["apacheconf", "ApacheConf"], ["applescript", "AppleScript"],
             ["as", "ActionScript"], ["as3", "ActionScript 3"], ["awk", "Awk"], ["basemake", "Base Makefile"],
             ["bash", "Bash"], ["bat", "Batchfile"], ["c", "C"], ["cheetah", "Cheetah"], ["clojure", "Clojure"],
             ["cmake", "CMake"], ["coffee-script", "CoffeeScript"], ["common-lisp", "Common Lisp"],
             ["cpp", "C++"], ["csharp", "C#"], ["css", "CSS"], ["d", "D"], ["dart", "Dart"], ["diff", "Diff"],
             ["django", "Django/Jinja"], ["erlang", "Erlang"], ["fortran", "Fortran"], ["fsharp", "FSharp"],
             ["go", "Go"], ["groovy", "Groovy"], ["haml", "Haml"], ["haskell", "Haskell"],
             ["html", "HTML"], ["html+php", "HTML+PHP"], ["http", "HTTP"], ["ini", "INI"],
             ["irc", "IRC logs"], ["jade", "Jade"], ["java", "Java"], ["js", "JavaScript"],
             ["json", "JSON"], ["jsp", "Java Server Page"], ["lighty", "Lighttpd configuration file"],
             ["llvm", "LLVM"], ["lua", "Lua"], ["make", "Makefile"], ["matlab", "Matlab"],
             ["mysql", "MySQL"], ["nasm", "NASM"], ["nginx", "Nginx configuration file"],
             ["objective-c", "Objective-C"], ["objective-j", "Objective-J"], ["ocaml", "OCaml"],
             ["octave", "Octave"], ["ooc", "Ooc"], ["perl", "Perl"], ["php", "PHP"], ["plpgsql", "PL/pgSQL"],
             ["postgresql", "PostgreSQL SQL dialect"], ["postscript", "PostScript"], ["pot", "Gettext Catalog"],
             ["prolog", "Prolog"], ["protobuf", "Protocol Buffer"], ["python", "Python"], ["python3", "Python 3"],
             ["rb", "Ruby"], ["sass", "Sass"], ["scala", "Scala"], ["scaml", "Scaml"], ["scheme", "Scheme"],
             ["scilab", "Scilab"], ["scss", "SCSS"], ["smalltalk", "Smalltalk"], ["smarty", "Smarty"],
             ["sql", "SQL"], ["tcl", "Tcl"], ["tex", "TeX"], ["text", "Text only"],
             ["trac-wiki", "MoinMoin/Trac Wiki markup"], ["v", "verilog"], ["vala", "Vala"],
             ["vb.net", "VB.net"], ["velocity", "Velocity"], ["vhdl", "vhdl"], ["vim", "VimL"],
             ["xml", "XML"], ["xslt", "XSLT"], ["yaml", "YAML"]];
exports.langs = langs;

exports.lang_by_shortcode = function(shortcode) {
    return langs.filter(function(li) {
        return li[0] === shortcode;
    }).reduceRight(function(a, b) {
        return a.concat(b);
    });
};
